BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
    Button:
        id: input_name
        text: ''
    Button:
        text: 'three'
    Label:
        text: 'Enter your name'
        color: (1, 1, 0, 1)
    Button:
         text: 'Greet'
         on_press: app.handle_greet()

id: output_label

self.root.ids.output_label.text = "Hello" + self.root.ids.input_name.text