BoxLayout:
    orientation: 'vertical' 
    BoxLayout:
        oreitnation: 'vertical'
        id: names_label
    TextInput:
        id: input_name
        size_hint_y: 0.5
        font_size: 48
        text: ''
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: "Insert New Entry"
            on_release: app.create_label(input_name.text)
        Button:
            text: "Clear Widgets"
            on_release: app.clear_all()
